# Generated by Django 5.2.8 on 2025-11-30 23:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(db_column='ID_Asignacion', primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now_add=True, db_column='Fecha_Solicitud')),
                ('cantidad_solicitada', models.IntegerField(db_column='Cantidad_Solicitada')),
                ('estado', models.CharField(db_column='Estado', max_length=9)),
            ],
            options={
                'db_table': 'asignacion',
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id_donacion', models.AutoField(db_column='ID_Donacion', primary_key=True, serialize=False)),
                ('fecha_oferta', models.DateField(auto_now_add=True, db_column='Fecha_Oferta')),
                ('estado', models.CharField(db_column='Estado', max_length=9)),
                ('total_equipos', models.IntegerField(db_column='Total_Equipos')),
            ],
            options={
                'db_table': 'donacion',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(db_column='ID_Equipo', primary_key=True, serialize=False)),
                ('num_serie', models.CharField(blank=True, db_column='Num_Serie', max_length=50, null=True, unique=True)),
                ('tipo', models.CharField(db_column='Tipo', max_length=7)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=100, null=True)),
                ('ram', models.CharField(blank=True, db_column='RAM', max_length=20, null=True)),
                ('almacenamiento', models.CharField(blank=True, db_column='Almacenamiento', max_length=50, null=True)),
                ('estado_inicial', models.TextField(blank=True, db_column='Estado_Inicial', null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos/', verbose_name='Foto del Equipo')),
                ('id_donacion', models.ForeignKey(db_column='ID_Donacion', on_delete=django.db.models.deletion.CASCADE, to='app1Backend.donacion')),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('rut', models.CharField(db_column='RUT', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('tipo', models.CharField(db_column='Tipo', max_length=9)),
                ('contacto_nombre', models.CharField(blank=True, db_column='Contacto_Nombre', max_length=100, null=True)),
                ('contacto_email', models.CharField(blank=True, db_column='Contacto_Email', max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, db_column='Comuna', max_length=100, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, db_column='Fecha_Registro')),
            ],
            options={
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('rol', models.CharField(db_column='Rol', max_length=13)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion', default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='app1Backend_usuario_set', related_query_name='usuario', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='app1Backend_usuario_permissions', related_query_name='usuario', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='DetalleAsignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField(blank=True, db_column='Fecha_Entrega', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('id_asignacion', models.ForeignKey(db_column='ID_Asignacion', on_delete=django.db.models.deletion.CASCADE, to='app1Backend.asignacion')),
                ('id_equipo', models.OneToOneField(db_column='ID_Equipo', on_delete=django.db.models.deletion.CASCADE, to='app1Backend.equipo')),
            ],
            options={
                'db_table': 'detalle_asignacion',
            },
        ),
        migrations.AddField(
            model_name='donacion',
            name='rut_institucion',
            field=models.ForeignKey(db_column='RUT_Institucion', on_delete=django.db.models.deletion.DO_NOTHING, to='app1Backend.institucion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='rut_institucion_receptora',
            field=models.ForeignKey(db_column='RUT_Institucion_Receptora', on_delete=django.db.models.deletion.DO_NOTHING, to='app1Backend.institucion'),
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id_soporte', models.AutoField(db_column='ID_Soporte', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=12)),
                ('fecha_evento', models.DateField(auto_now_add=True, db_column='Fecha_Evento')),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('resolucion', models.TextField(blank=True, db_column='Resolucion', null=True)),
                ('id_asignacion', models.ForeignKey(db_column='ID_Asignacion', on_delete=django.db.models.deletion.CASCADE, to='app1Backend.asignacion')),
                ('id_tecnico', models.ForeignKey(blank=True, db_column='ID_Tecnico', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'soporte',
            },
        ),
        migrations.CreateModel(
            name='Reacondicionamiento',
            fields=[
                ('id_equipo', models.OneToOneField(db_column='ID_Equipo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1Backend.equipo')),
                ('taller_asignado', models.CharField(blank=True, db_column='Taller_Asignado', max_length=150, null=True)),
                ('fecha_inicio', models.DateField(blank=True, db_column='Fecha_Inicio', null=True)),
                ('fecha_fin', models.DateField(blank=True, db_column='Fecha_Fin', null=True)),
                ('acciones_realizadas', models.TextField(blank=True, db_column='Acciones_Realizadas', null=True)),
                ('estado_final', models.CharField(db_column='Estado_Final', max_length=10)),
                ('evidencia_final', models.ImageField(blank=True, null=True, upload_to='reacondicionamiento/', verbose_name='Foto del trabajo final')),
                ('id_tecnico', models.ForeignKey(blank=True, db_column='ID_Tecnico', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reacondicionamiento',
            },
        ),
    ]
