# Generated by Django 5.2.8 on 2025-12-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reacondicionamiento',
            name='estado_final',
            field=models.CharField(db_column='Estado_Final', max_length=20),
        ),
    ]
