# Generated by Django 5.2.6 on 2025-11-06 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalleasignacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='detalleasignacion',
            name='id_asignacion',
            field=models.ForeignKey(db_column='ID_Asignacion', on_delete=django.db.models.deletion.CASCADE, to='app1Backend.asignacion'),
        ),
        migrations.AlterField(
            model_name='detalleasignacion',
            name='id_equipo',
            field=models.OneToOneField(db_column='ID_Equipo', on_delete=django.db.models.deletion.CASCADE, to='app1Backend.equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_donacion',
            field=models.ForeignKey(db_column='ID_Donacion', on_delete=django.db.models.deletion.CASCADE, to='app1Backend.donacion'),
        ),
        migrations.AlterField(
            model_name='reacondicionamiento',
            name='id_equipo',
            field=models.OneToOneField(db_column='ID_Equipo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1Backend.equipo'),
        ),
        migrations.AlterField(
            model_name='reacondicionamiento',
            name='id_tecnico',
            field=models.ForeignKey(blank=True, db_column='ID_Tecnico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1Backend.usuario'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='id_tecnico',
            field=models.ForeignKey(blank=True, db_column='ID_Tecnico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1Backend.usuario'),
        ),
    ]
